[package]
name = "rust-deploy"
version = "0.1.0"
authors = ["Ronan <ronan_mccabe@protonmail.com>"]
edition = "2018"

[dependencies]
http = "0.1.18"
reqwest = "0.9.19"
juniper = "0.13.1"
serde_json = "1.0.40"
now_lambda = "0.1.3"
